<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Osq_DpP' shared service.

return $this->privates['.service_locator.Osq_DpP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'categories' => ['privates', 'App\\Utils\\CategoryTreeFrontPage', 'getCategoryTreeFrontPageService.php', true],
    'video_no_members' => ['privates', 'App\\Utils\\VideoForNoValidSubscription', 'getVideoForNoValidSubscriptionService.php', true],
]);
