<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.I.ArnNt' shared service.

return $this->privates['.service_locator.I.ArnNt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'video_no_members' => ['privates', 'App\\Utils\\VideoForNoValidSubscription', 'getVideoForNoValidSubscriptionService.php', true],
]);
