<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sb_redis.default' shared service.

include_once $this->targetDirs[3].'\\vendor\\predis\\predis\\src\\ClientInterface.php';
include_once $this->targetDirs[3].'\\vendor\\predis\\predis\\src\\Client.php';
include_once $this->targetDirs[3].'\\vendor\\symfony-bundles\\redis-bundle\\Redis\\ClientInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony-bundles\\redis-bundle\\Redis\\Client.php';
include_once $this->targetDirs[3].'\\vendor\\symfony-bundles\\redis-bundle\\Redis\\FactoryInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony-bundles\\redis-bundle\\Redis\\Factory.php';

return $this->services['sb_redis.default'] = ($this->privates['SymfonyBundles\\RedisBundle\\Redis\\FactoryInterface'] ?? ($this->privates['SymfonyBundles\\RedisBundle\\Redis\\FactoryInterface'] = new \SymfonyBundles\RedisBundle\Redis\Factory()))->create([0 => $this->getEnv('REDIS_URL')], []);
