<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.XhFqX8r' shared service.

return $this->privates['.service_locator.XhFqX8r'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'categories' => ['privates', 'App\\Utils\\CategoryTreeAdminList', 'getCategoryTreeAdminListService.php', true],
]);
