<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.bKAxWeC' shared service.

return $this->privates['.service_locator.bKAxWeC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'repo' => ['privates', 'App\\Repository\\VideoRepository', 'getVideoRepositoryService.php', true],
    'video_no_members' => ['privates', 'App\\Utils\\VideoForNoValidSubscription', 'getVideoForNoValidSubscriptionService.php', true],
]);
