<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Utils\LocalUploader' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Utils\\Interfaces\\UploaderInterface.php';
include_once $this->targetDirs[3].'\\src\\Utils\\LocalUploader.php';

return $this->privates['App\\Utils\\LocalUploader'] = new \App\Utils\LocalUploader(($this->targetDirs[3].'/public/uploads/videos'));
