<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Utils\VideoForNoValidSubscription' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Utils\\VideoForNoValidSubscription.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\security-core\\Security.php';

return $this->privates['App\\Utils\\VideoForNoValidSubscription'] = new \App\Utils\VideoForNoValidSubscription(new \Symfony\Component\Security\Core\Security(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'security.authorization_checker' => ['services', 'security.authorization_checker', 'getSecurity_AuthorizationCheckerService', false],
    'security.token_storage' => ['services', 'security.token_storage', 'getSecurity_TokenStorageService', false],
])));
