<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFxNroN1\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFxNroN1/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFxNroN1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFxNroN1\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFxNroN1\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'FxNroN1',
    'container.build_id' => '68b4eb9c',
    'container.build_time' => 1562686427,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFxNroN1');
